services:
  - type: web
    name: meeting-app
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20.20.2
      - key: NODE_ENV
        value: production
    healthCheckPath: /ping
    autoDeploy: true
    websocket: true
    scaling:
      minInstances: 1
      maxInstances: 1
    port: 3000
    headers:
      - path: /*
        name: X-Forwarded-Proto
        value: https
